version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        links:
            - "php:php"
        volumes:
            - "./wordpress:/home/docker"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            # - "/etc/letsencrypt:/etc/letsencrypt"
    php:
        build: "./docker/php"
        volumes:
            - "./wordpress:/home/docker"
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
        links:
            - "mysql:mysql"
        working_dir: "/home/docker"
    mysql:
        image: mysql:8.0.0
        ports:
            - "3306:3306"
        volumes:
            - "./backup:/backup"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=hello"
            - "MYSQL_DATABASE=wordpress"
